CREATE INDEX "INDEX_BUDDLE" ON "BUDDLE" (
   "IDENTIFIER" ASC
);

CREATE INDEX "INDEX_CATALOG" ON "CATALOG" (
   "BUDDLE_ID" ASC,
   "IDENTIFIER" ASC
);

CREATE INDEX "INDEX_LANGUAGE" ON "LANGUAGE" (
   "NAME" ASC
);

CREATE INDEX "INDEX_PROCESSOR" ON "PROCESSOR" (
   "CLASS" ASC
);

CREATE INDEX "INDEX_STYLE" ON "STYLE" (
   "IDENTIFIER" ASC
);

